<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Company>sockless-coding</Company>
    <Authors>Jimmy Everling</Authors>
    <Product>Sockless npm Package Manager for Visual Studio</Product>
    <Copyright>Copyright (c) Jimmy Everling</Copyright>
    <RepositoryUrl>https://github.com/sockless-coding/vs-npm-manager</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

</Project>
